name: output information
on: [workflow_dispatch]
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps: 
      - name: my github context
        run: echo "${{ toJSON(github )}}" # For printing our any dynamic variab;s we will be using ${{ github }}
        # This github key value will provide information regarding workflow run

